### ISSUE TITLE
demo link is 404

### ISSUE THREAD

**Issue by warmthsea** [chengpeiquan/vpc-nux3-demo#1]

**Comment by chengpeiquan** [comment]
Sorry for the typo in the URL: 'nux3' -> 'nuxt3', I fixed it now.
https://chengpeiquan.github.io/vpc-nuxt3-demo/

**Comment by warmthsea** [comment]
> 很抱歉 URL 中的错字：'nux3' -> 'nuxt3'，我现在修正了它。 https://chengpeiquan.github.io/vpc-nuxt3-demo/
你的插件很不错，我在社区内没有找到其它兼容Nuxt3的插件(其它Vue插件往往需要配置很多参数)，总之，他帮了我忙，感谢
